#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2023 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#

ARCH="arm64"

LINUXFAMILY="sun50iw10-syterkit"
#enable_extension "syterkit-allwinner"

case "${BRANCH}" in

	legacy)
		KERNELSOURCE='https://github.com/chainsx/kernel-sun50iw10.git'
		KERNELBRANCH="branch:master"
		declare -g KERNEL_MAJOR_MINOR="5.15"
		KERNELPATCHDIR="sun50iw10-syterkit-${BRANCH}"
		LINUXCONFIG="linux-sun50iw10-syterkit-${BRANCH}"

		;;

esac

write_uboot_platform() {
	dd if=/dev/zero of=$2 bs=1k count=1023 seek=1 status=noxfer > /dev/null 2>&1
	dd if="$SRC/packages/blobs/sunxi/sun50iw10/100ask_ros_extlinux_boot_bin_card.bin" of=$2 bs=1024 seek=8 status=noxfer > /dev/null 2>&1
}
