#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2023 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#

ARCH="arm64"

LINUXFAMILY="sun55iw6"

IMAGE_PARTITION_TABLE="msdos"
BOOTFS_TYPE="fat"
BOOTSIZE="512"
OFFSET="32"
EXTRAWIFI="no"
KERNEL_BTF="no"
ATF_COMPILE="no"

case "${BRANCH}" in

	legacy)
		KERNELSOURCE='https://github.com/chainsx/linux-sun55iw6-vendor.git'
		# This is Allwinner's new BSP kernel,
		# which consists of a specific version of the mainline kernel source code and a folder containing BSP driver source code files.
		KERNELBRANCH="branch:linux-5.10"
		declare -g KERNEL_MAJOR_MINOR="5.10"
		KERNELPATCHDIR="sun55iw6-${BRANCH}"
		LINUXCONFIG="linux-sun55iw6-${BRANCH}"

		;;

esac

write_uboot_platform() {
	dd if=$SRC/packages/blobs/sunxi/sun55iw6/boot0_sdcard.fex of=$2 bs=8k seek=1 conv=notrunc
	dd if=$SRC/packages/blobs/sunxi/sun55iw6/boot_package.fex of=$2 bs=8k seek=2050 conv=notrunc
}
