# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#
setenv rootdev "/dev/mmcblk1p1"
setenv rootfs "ext4"
setenv verbosity "1"
setenv devtype "mmc"
setenv prefix "boot/"

echo "Boot script loaded from device ${mmcdev}"

if test -e ${devtype} ${mmcdev} ${prefix}armbianEnv.txt; then
	load ${devtype} ${mmcdev} ${kernel_addr_r} ${prefix}armbianEnv.txt
	env import -t ${kernel_addr_r} ${filesize}
fi


setenv bootargs "rw rootwait earlycon loglevel=${verbosity} root=${rootdev} rootfstype=${rootfstype}"
ext4load ${devtype} ${mmcdev}:${mmcbootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
ext4load ${devtype} ${mmcdev}:${mmcbootpart} ${ramdisk_addr_r} ${prefix}uInitrd
ext4load ${devtype} ${mmcdev}:${mmcbootpart} ${kernel_addr_r} ${prefix}Image
echo "Booting Image uInitrd ${fdtfile} from: ${devtype} ${mmcdev}:${mmcpart} using bootargs=${bootargs}"
booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}
# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
